#!/bin/bash -e
# Title: spm
# Description: Downloads and installs AppImages and precompiled tar archives.  Can also upgrade and remove installed packages.
# Dependencies: GNU coreutils, tar, wget
# Author: simonizor
# Website: http://www.simonizor.gq
# License: GPL v2.0 only

X="0.5.5"
# Set spm version
CONFDIR="$HOME/.config/spm"
SKIP_DEP_CHECKS="FALSE"

if [ "$EUID" = "0" ]; then # Prevent spm from being ran as root
    echo "Do not run spm as root!"
    exit 1
fi

if [ -f ~/.config/spm/spm.conf ]; then
    . ~/.config/spm/spm.conf
fi

if [ ! -d "$CONFDIR" ]; then # Create dirs for configs, config files, and download package lists if they don't exist
    echo "spm is being ran for the first time."
    echo "Creating config directories..."
    mkdir "$CONFDIR"
    mkdir "$CONFDIR"/tarinstalled
    mkdir "$CONFDIR"/appimginstalled
    mkdir "$CONFDIR"/tarupgrades
    mkdir "$CONFDIR"/appimgupgrades
    mkdir "$CONFDIR"/cache
    echo "CONFDIR="\"$CONFDIR\""" > "$CONFDIR"/spm.conf
    echo "GITHUB_TOKEN="\"\""" >> "$CONFDIR"/spm.conf
    echo "SKIP_DEP_CHECKS="\"FALSE\""" >> "$CONFDIR"/spm.conf
    echo "First run operations complete!"
fi

if [ ! -f "$CONFDIR/AppImages.yml" ]; then
    echo "Downloading AppImages.yml from spm github..."
    wget --quiet "https://raw.githubusercontent.com/simoniz0r/spm-repo/master/AppImages.yml" -O "$CONFDIR"/AppImages.yml
    echo "Downloading tar-pkgs.yml from spm github repo..."
    wget --quiet "https://raw.githubusercontent.com/simoniz0r/spm-repo/master/tar-pkgs.yml" -O "$CONFDIR"/tar-pkgs.yml
fi

REALPATH="$(readlink -f $0)"
RUNNING_DIR="$(dirname "$REALPATH")" # Find directory script is running from
if [ -f $RUNNING_DIR/spmfunctions.sh ]; then # Check to make sure spmfunctions.sh exists and is up to date
    FUNCTIONS_VER="$(cat "$RUNNING_DIR"/spmfunctions.sh | sed -n 9p | cut -f2 -d'"')"
    if [ "$X" != "$FUNCTIONS_VER" ]; then
        echo "$$(tput setaf 1)spmfunctions.sh $FUNCTIONS_VER version does not match $X !"
        echo "spmfunctions.sh is out of date! Please download the full release of spm from https://github.com/simoniz0r/spm/releases !$(tput sgr0)"
        exit 1
    fi
else
    echo "$(tput setaf 1)Missing required file $RUNNING_DIR/spmfunctions.sh !"
        echo "spmfunctions.sh is missing! Please download the full release of spm from https://github.com/simoniz0r/spm/releases !$(tput sgr0)"
        exit 1
fi
source "$RUNNING_DIR"/spmfunctions.sh || { echo "Sourcing spmfunctions.sh failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from spmfunctions.sh

spmdepchecksfunc || { echo "$(tput setaf 1)Could not load $RUNNING_DIR/spmfunctions.sh; exiting...$(tput sgr0)"; exit 1; } # Check for deps, exit if not present

if type spm >/dev/null 2>&1 && [ -f ~/.zshrc ] && ! grep -q 'spm.comp' ~/.zshrc; then # If using zsh and spm is installed, add tab completions for spm
    wget --quiet "https://raw.githubusercontent.com/simoniz0r/spm/master/spm.comp" -O "$CONFDIR"/spm.comp
    echo "" >> ~/.zshrc
    echo "if [ -f "$CONFDIR"/spm.comp ]; then" >> ~/.zshrc
    echo "    source "$CONFDIR"/spm.comp" >> ~/.zshrc
    echo "    compdef _spm spm" >> ~/.zshrc
    echo "fi" >> ~/.zshrc
    echo "" >> ~/.zshrc
fi

appimgfunctioncheckfunc # Check to make sure appimgfunctions.sh exists and is up to date
source "$RUNNING_DIR"/appimgfunctions.sh || { echo "Sourcing appingfunctions.sh failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from appimgfunctions.sh
appimgfunctionsexistsfunc  || { echo "$(tput setaf 1)Could not load $RUNNING_DIR/appimgfunctions.sh; exiting...$(tput sgr0)"; exit 1; }

tarfunctioncheckfunc # Check to make sure tarfunctions.sh exists and is up to date
source "$RUNNING_DIR"/tarfunctions.sh || { echo "Sourcing tarfunctions.sh failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # import functions from tarfunctions.sh
tarfunctionsexistfunc || { echo "$(tput setaf 1)Could not load $RUNNING_DIR/tarfunctions.sh; exiting...$(tput sgr0)"; exit 1; }

spmlockfunc # Create "$CONFDIR"/cache/spm.lock file and prevent multiple instances by checking if it exists before running

if [ -z "$GITHUB_TOKEN" ]; then # Display github rate limit by using wget to show https://api.github.com/rate_limit
    wget -S --spider "https://api.github.com/rate_limit" -o "$CONFDIR"/cache/rate.limit
    echo "Github API rate limit: $(grep -m 1 '.*X-RateLimit-Remaining:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ")/60 until $(date -d@$(grep -m 1 '.*X-RateLimit-Reset:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ") +"%T, %F")."  || { echo "Github rate limit check failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; }
else
    wget -S --spider --quiet --auth-no-challenge --header="Authorization: token "$GITHUB_TOKEN"" "https://api.github.com/rate_limit" -o "$CONFDIR"/cache/rate.limit  || { echo "Github rate limit check failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; }
    echo "Github API rate limit : $(grep -m 1 '.*X-RateLimit-Remaining:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ")/5000 until $(date -d@$(grep -m 1 '.*X-RateLimit-Reset:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ") +"%T, %F")."
fi
if [ "$(grep -m 1 '.*X-RateLimit-Remaining:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" ")" = "0" ]; then # Attempt to exit to prevent errors if user's github rate limit has been used up
    echo "$(tput setaf 1)Github API rate limit reached! Try again at $(date -d@$(grep -m 1 '.*X-RateLimit-Reset:*.' "$CONFDIR"/cache/rate.limit | cut -f4 -d" "))."
    echo "If you haven't already, you can add your token to $CONFDIR/spm.conf"
    echo "to avoid hitting the rate limit.$(tput sgr0)"
    rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
    exit 1
fi
echo

case $1 in
    install|-i|appimg-install|-ai|tarinstall|-ti) # Check if package is in either list and rout install to relevant function
        if [ -z "$2" ]; then
            echo "$(tput setaf 1)Package input required; exiting...$(tput sgr0)"
            rm -rf "$CONFDIR"/cache/*
            exit 1
        fi
        TESTPKG="$2"
        installstartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Check package lists and route install to relevant function
        rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
        exit 0
        ;;
    update|-upd) # Update package lists and check for package upgrades
        spmvercheckfunc || { echo "spm version check failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Check spm version and let user know if it is out of date
        updatestartfunc "$2" || { echo "Upgrade check failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Send input to relevant update function or run both if no input
        rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
        exit 0
        ;;
    update-force|-uf|appimg-update-force|-auf|tar-update-force|-tuf) # Force AppImage to be marked for upgrade
        if [ -z "$2" ]; then
            echo "$(tput setaf 1)Package input required; exiting...$(tput sgr0)"
            rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
            exit 1
        fi
        TESTUF="$2"
        updateforcestartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; }
        rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
        exit 0
        ;;
    upgrade|-upg) # upgrade packages to latest version if marked for upgrade
        upgradestartfunc "$2" || { echo "Upgrade failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Check which (if any) package types have upgrades and run relevant functions
        rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
        exit 0
        ;;
    remove|-r|appimg-remove|-ar|tar-remove|-tr)
        if [ -z "$2" ]; then
            echo "$(tput setaf 1)Package input required; exiting...$(tput sgr0)"
            rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
            exit 1
        fi
        TESTREM="$2"
        removestartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; }
        rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
        exit 0
        ;;
    list|-l) # List installed packages or info about specified package
        INSTIMG="$2"
        TARPKG="$2"
        liststartfunc || { echo "Failed; exiting..."; rm -rf "$CONFDIR"/cache/*; exit 1; } # Send package input to relevant list function or run both if no input
        rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
        exit 0
        ;;
    list-installed|-li) # List information about installed packages
        listinstalledfunc | less -R
        rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
        exit 0
        ;;
    search|-s) # Use grep to search package lists based on user input and output matching packages and which list they are in
        if cat "$CONFDIR"/AppImages.yml | cut -f1 -d":" | grep -q "$2"; then
            echo "$(tput bold)$(tput setaf 2)AppImage(s)$(tput sgr0):"
            cat "$CONFDIR"/AppImages.yml | cut -f1 -d":" | grep "$2"
            echo
        fi
        if echo "$TAR_LIST" | grep -q "$2"; then
            echo "$(tput bold)$(tput setaf 6)tar package(s)$(tput sgr0):"
            echo "$TAR_LIST" | grep "$2"
            echo
        fi
        rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
        exit 0
        ;;
    man|-m) # run man $RUNNING_DIR/spm.1 to show spm's man file
        man $RUNNING_DIR/spm.1
        rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
        exit 0
        ;;
    *) # Any unknown arguments go to help func
        helpfunc
        rm -rf "$CONFDIR"/cache/* # Remove any files in cache before exiting
        exit 0
        ;;
esac
